<?php
require dirname(__DIR__) . '/panel/navigation.php';

$esc = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$sourceUrl = function_exists('route')
    ? route('surveillance.report.abnormal', request()->only(['declaration_id', 'employee_id', 'company_id', 'surveillance_id']))
    : 'surveillance_abnormalReport.php';
$resolvedUser = class_exists('\\Illuminate\\Support\\Facades\\Auth') ? \Illuminate\Support\Facades\Auth::user() : null;
$footerFirst = trim((string) (($resolvedUser->first_name ?? $resolvedUser->firstName ?? '') ?: ''));
$footerLast = trim((string) (($resolvedUser->last_name ?? $resolvedUser->lastName ?? '') ?: ''));
$footerName = trim($footerFirst . ' ' . $footerLast);
if ($footerName === '') {
    $footerName = trim((string) (($resolvedUser->name ?? $username ?? 'User') ?: 'User'));
}
$generatedFooter = 'Generated by ' . $footerName . ' at ' . date('D, d M Y h:i A');

medis_render_navigation_start([
    'clinicName' => $clinicName ?? 'Medis SHAMS',
    'clinicLogoUrl' => $clinicLogoUrl ?? null,
    'username' => $username ?? 'User',
    'active' => 'report',
]);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PDF USECHH 5ii</title>
</head>
<body>
<style>
.pdf-page{display:grid;gap:12px;color:#0f172a;font-family:"Poppins","Segoe UI",Tahoma,Geneva,Verdana,sans-serif}
.preview-toolbar{display:flex;justify-content:flex-end}
.print-btn{display:inline-flex;align-items:center;justify-content:center;padding:10px 18px;border:1px solid #2f9e44;border-radius:999px;background:#2f9e44;color:#fff;font:inherit;font-weight:700;cursor:pointer}
.preview-iframe{display:block;width:100%;height:980px;border:0;background:#fff}
.pdf-footer{padding-top:8px;border-top:1px solid #e5e7eb;text-align:right;font-size:11px;color:#64748b}
</style>
<div class="pdf-page">
    <div class="preview-toolbar">
        <button class="print-btn" type="button" onclick="printPdfPreview()">Print Report</button>
    </div>
    <iframe class="preview-iframe" name="pdfPreviewFrame" src="<?php echo $esc($sourceUrl); ?>" title="PDF USECHH 5ii preview"></iframe>
    <div class="pdf-footer"><?php echo $esc($generatedFooter); ?></div>
</div>
<script>
function printPdfPreview() {
    var frame = window.frames.pdfPreviewFrame;
    if (!frame) {
        window.print();
        return;
    }
    frame.focus();
    frame.print();
}
</script>
<?php medis_render_navigation_end(); ?>
</body>
</html>
