<?php
require dirname(__DIR__) . '/panel/navigation.php';

$esc = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$sourceUrl = function_exists('route')
    ? route('audiometry.report', request()->only(['audiometry_id', 'employee_id', 'company_id']))
    : 'audiometry_report.php';
$resolvedUser = class_exists('\\Illuminate\\Support\\Facades\\Auth') ? \Illuminate\Support\Facades\Auth::user() : null;
$footerFirst = trim((string) (($resolvedUser->first_name ?? $resolvedUser->firstName ?? '') ?: ''));
$footerLast = trim((string) (($resolvedUser->last_name ?? $resolvedUser->lastName ?? '') ?: ''));
$footerName = trim($footerFirst . ' ' . $footerLast);
if ($footerName === '') {
    $footerName = trim((string) (($resolvedUser->name ?? $username ?? 'User') ?: 'User'));
}
$generatedFooter = 'Generated by ' . $footerName . ' at ' . date('D, d M Y h:i A');

medis_render_navigation_start([
    'clinicName' => $clinicName ?? 'Medis SHAMS',
    'clinicLogoUrl' => $clinicLogoUrl ?? null,
    'username' => $username ?? 'User',
    'active' => 'report',
]);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PDF Audio Report</title>
</head>
<body>
<style>
.pdf-page{display:grid;gap:12px;color:#0f172a;font-family:"Poppins","Segoe UI",Tahoma,Geneva,Verdana,sans-serif}
.toolbar{display:flex;justify-content:flex-end}
.next{display:inline-flex;align-items:center;gap:8px;text-decoration:none;border:1px solid #389B5B;border-radius:12px;padding:10px 16px;background:#389B5B;color:#fff;font:inherit;cursor:pointer}
.preview-iframe{display:block;width:100%;height:980px;border:0;background:#fff}
.pdf-footer{padding-top:8px;border-top:1px solid #e5e7eb;text-align:right;font-size:11px;color:#64748b}
</style>
<div class="pdf-page">
    <div class="toolbar">
        <button class="next" type="button" onclick="window.frames['pdfPreviewFrame'].print()">Print Report</button>
    </div>
    <iframe class="preview-iframe" name="pdfPreviewFrame" src="<?php echo $esc($sourceUrl); ?>" title="PDF Audio Report preview"></iframe>
    <div class="pdf-footer"><?php echo $esc($generatedFooter); ?></div>
</div>
<?php medis_render_navigation_end(); ?>
</body>
</html>
